const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  auth: {
    check:    ()     => ipcRenderer.invoke('auth:check'),
    register: (data) => ipcRenderer.invoke('auth:register', data),
    login:    (data) => ipcRenderer.invoke('auth:login', data),
  },
  routes: {
    get:               ()     => ipcRenderer.invoke('routes:get'),
    add:               (data) => ipcRenderer.invoke('routes:add', data),
    edit:              (data) => ipcRenderer.invoke('routes:edit', data),
    delete:            (data) => ipcRenderer.invoke('routes:delete', data),
    browse:            (data) => ipcRenderer.invoke('routes:browse', data),
    folderSize:        (data) => ipcRenderer.invoke('routes:folderSize', data),
    openFile:          (data) => ipcRenderer.invoke('routes:openFile', data),
    downloadZip:       (data) => ipcRenderer.invoke('routes:downloadZip', data),
    getEffectiveAccess:(data) => ipcRenderer.invoke('routes:getEffectiveAccess', data),
  },
  friends: {
    get:               ()     => ipcRenderer.invoke('friends:get'),
    add:               (data) => ipcRenderer.invoke('friends:add', data),
    remove:            (data) => ipcRenderer.invoke('friends:remove', data),
    updateUrl:         (data) => ipcRenderer.invoke('friends:updateUrl', data),
    getStatus:         ()     => ipcRenderer.invoke('friends:getStatus'),
    setAlias:          (data) => ipcRenderer.invoke('friends:setAlias', data),
    getAliases:        ()     => ipcRenderer.invoke('friends:getAliases'),
    sendRequest:       (data) => ipcRenderer.invoke('friends:sendRequest', data),
    getPendingRequests:()     => ipcRenderer.invoke('friends:getPendingRequests'),
    acceptRequest:     (data) => ipcRenderer.invoke('friends:acceptRequest', data),
    rejectRequest:     (data) => ipcRenderer.invoke('friends:rejectRequest', data),
    verify:            (data) => ipcRenderer.invoke('friends:verify', data),
  },
  families: {
    get:            ()     => ipcRenderer.invoke('families:get'),
    create:         (data) => ipcRenderer.invoke('families:create', data),
    rename:         (data) => ipcRenderer.invoke('families:rename', data),
    delete:         (data) => ipcRenderer.invoke('families:delete', data),
    invite:         (data) => ipcRenderer.invoke('families:invite', data),
    acceptInvite:   (data) => ipcRenderer.invoke('families:acceptInvite', data),
    rejectInvite:   (data) => ipcRenderer.invoke('families:rejectInvite', data),
    leave:          (data) => ipcRenderer.invoke('families:leave', data),
    addMember:      (data) => ipcRenderer.invoke('families:addMember', data),
    removeMember:   (data) => ipcRenderer.invoke('families:removeMember', data),
    promoteMember:  (data) => ipcRenderer.invoke('families:promoteMember', data),
    demoteMember:   (data) => ipcRenderer.invoke('families:demoteMember', data),
    setRouteFamily: (data) => ipcRenderer.invoke('families:setRouteFamily', data),
    sendChat:       (data) => ipcRenderer.invoke('families:sendChat', data),
    onChatMessage:  (fn)   => ipcRenderer.on('family:chatMessage', (_, ...args) => fn(...args)),
  },
  p2p: {
    getMyAddress:   ()     => ipcRenderer.invoke('p2p:getMyAddress'),
    getMyAddString: ()     => ipcRenderer.invoke('p2p:getMyAddString'),
    getFingerprint: (data) => ipcRenderer.invoke('p2p:getFingerprint', data),
    connect:        (data) => ipcRenderer.invoke('p2p:connect', data),
    browse:         (data) => ipcRenderer.invoke('p2p:browse', data),
    folderSize:     (data) => ipcRenderer.invoke('p2p:folderSize', data),
    downloadFile:   (data) => ipcRenderer.invoke('p2p:downloadFile', data),
    downloadZip:    (data) => ipcRenderer.invoke('p2p:downloadZip', data),
    getFamilyMemberRoutes: (data) => ipcRenderer.invoke('p2p:getFamilyMemberRoutes', data),
    search:         (data) => ipcRenderer.invoke('p2p:search', data),
    onSearchResult: (fn)   => ipcRenderer.on('p2p:searchResult', (_, ...args) => fn(...args)),
    getSignedUrl:   (data) => ipcRenderer.invoke('p2p:getSignedUrl', data),
    getDownloadQueue: ()   => ipcRenderer.invoke('p2p:getDownloadQueue'),
    onDownloadProgress: (fn) => ipcRenderer.on('download:progress', (_, ...args) => fn(...args)),
  },
  system: {
    selectFolder:   ()     => ipcRenderer.invoke('system:selectFolder'),
    minimize:       ()     => ipcRenderer.send('system:minimize'),
    maximize:       ()     => ipcRenderer.send('system:maximize'),
    close:          ()     => ipcRenderer.send('system:close'),
    openDataFolder: ()     => ipcRenderer.send('system:openDataFolder'),
    checkUpdates:   ()     => ipcRenderer.send('system:checkUpdates'),
    getAutostart:   ()     => ipcRenderer.invoke('system:getAutostart'),
    setAutostart:   (data) => ipcRenderer.invoke('system:setAutostart', data),
    getAccessLog:   ()     => ipcRenderer.invoke('system:getAccessLog'),
    getSecurityLog: ()     => ipcRenderer.invoke('system:getSecurityLog'),
  },
  activity: {
    getHistory: () => ipcRenderer.invoke('activity:getHistory'),
  },
  settings: {
    getResourceConfig:  () => ipcRenderer.invoke('settings:getResourceConfig'),
    setResourceConfig:  (data) => ipcRenderer.invoke('settings:setResourceConfig', data),
  },
  identity: {
    export:        (data) => ipcRenderer.invoke('identity:export', data),
    import:        (data) => ipcRenderer.invoke('identity:import', data),
    setPassword:   (data) => ipcRenderer.invoke('identity:setPassword', data),
    deleteAccount: ()     => ipcRenderer.invoke('identity:deleteAccount'),
  },
  on: (channel, fn) => {
    const allowed = [
      'tunnel:status',
      'friends:statusUpdate',
      'friends:tunnelUpdated',
      'friends:requestReceived',
      'friends:requestAccepted',
      'zip:progress',
      'families:inviteReceived',
      'families:memberJoined',
      'families:memberLeft',
      'families:removedFromFamily',
      'families:synced',
      'activity:new',
    ];
    if (allowed.includes(channel)) {
      ipcRenderer.on(channel, (_, ...args) => fn(...args));
    }
  },
});
